<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Customize\Repository\ReceiptRepository' shared autowired service.

include_once $this->targetDirs[3].'\\app\\Customize\\Repository\\ReceiptRepository.php';

return $this->services['Customize\\Repository\\ReceiptRepository'] = new \Customize\Repository\ReceiptRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Doctrine\\Query\\Queries']) ? $this->services['Eccube\\Doctrine\\Query\\Queries'] : ($this->services['Eccube\\Doctrine\\Query\\Queries'] = new \Eccube\Doctrine\Query\Queries())) && false ?: '_'});
