<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWji63bn\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWji63bn/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWji63bn.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\ContainerWji63bn\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \ContainerWji63bn\EccubeProdProjectContainer([
    'container.build_hash' => 'Wji63bn',
    'container.build_id' => 'd28a0ad5',
    'container.build_time' => 1615956510,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWji63bn');
