<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRq9pvbo\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRq9pvbo/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRq9pvbo.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\ContainerRq9pvbo\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \ContainerRq9pvbo\EccubeProdProjectContainer([
    'container.build_hash' => 'Rq9pvbo',
    'container.build_id' => '034f4aee',
    'container.build_time' => 1615374925,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRq9pvbo');
