<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 * 
 * Creating HlDeliveryListRepository.
 * By MiMiKo 
 * Created at 2020-19-18
 * Version 4.0.4
 */

namespace Customize\Repository;

use Eccube\Doctrine\Query\Queries;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Eccube\Entity\Order;

/**
 * ReceiptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceiptRepository extends AbstractRepository
{
    /**
     * @var Queries
     */
    protected $queries;

    /**
     * ReceiptRepository constructor.
     *
     * @param RegistryInterface $registry
     * @param Queries $queries
     */
    public function __construct(
        RegistryInterface $registry,
        Queries $queries
    ) {
        parent::__construct($registry, Order::class);
        $this->queries = $queries;
    }

    /**
     * Find the Order with orderID
     *
     * @param int $id
     *
     * @return Order
     */
    public function findOrderWithID($id)
    {
      $result = null;
      try {
          $result = $this->createQueryBuilder('o')
            ->where('o.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleResult();
      } catch (\Exception $e) {
          return null;
      }

      return $result;
    }
}
